### PR TITLE
Enablement of recent version of HIP-VS plugin in vcxproj files:

### PR DESCRIPTION
**Pull request by hchevanne**
**Enablement of recent version of HIP-VS plugin in vcxproj files**
The current version of the HIP-VS extension introduce support of the nvcc compiler.
The formerly called "HIP toolchain" is then renamed as "HIP_clang" and the "HIP_nvcc" toolchain  has been introduced.
All 48 vcxproj files are updated accordingly:

- Applications/floyd_warshall/floyd_warshall_vs2019.vcxproj
- HIP-Basic/assembly_to_executable/assembly_to_executable_vs2019.vcxproj
- HIP-Basic/bandwidth/bandwidth_vs2019.vcxproj
- HIP-Basic/bit_extract/bit_extract_vs2019.vcxproj
- HIP-Basic/cooperative_groups/cooperative_groups_vs2019.vcxproj
- HIP-Basic/device_globals/device_globals_vs2019.vcxproj
- HIP-Basic/device_query/device_query_vs2019.vcxproj
- HIP-Basic/dynamic_shared/dynamic_shared_vs2019.vcxproj
- HIP-Basic/events/events_vs2019.vcxproj
- HIP-Basic/gpu_arch/gpu_arch_vs2019.vcxproj
- HIP-Basic/inline_assembly/inline_assembly_vs2019.vcxproj
- HIP-Basic/llvm_ir_to_executable/llvm_ir_to_executable_vs2019.vcxproj
- HIP-Basic/matrix_multiplication/matrix_multiplication_vs2019.vcxproj
- HIP-Basic/module_api/module_api_vs2019.vcxproj
- HIP-Basic/moving_average/moving_average_vs2019.vcxproj
- HIP-Basic/multi_gpu_data_transfer/multi_gpu_data_transfer_vs2019.vcxproj
- HIP-Basic/occupancy/occupancy_vs2019.vcxproj
- HIP-Basic/opengl_interop/opengl_interop_vs2019.vcxproj
- HIP-Basic/runtime_compilation/runtime_compilation_vs2019.vcxproj
- HIP-Basic/saxpy/saxpy_vs2019.vcxproj
- HIP-Basic/shared_memory/shared_memory_vs2019.vcxproj
- HIP-Basic/static_host_library/library/libhip_static_host_vs2019.vcxproj
- HIP-Basic/static_host_library/static_host_library_vs2019.vcxproj
- HIP-Basic/streams/streams_vs2019.vcxproj
- HIP-Basic/texture_management/texture_management_vs2019.vcxproj
- HIP-Basic/vulkan_interop/vulkan_interop_vs2019.vcxproj
- HIP-Basic/warp_shuffle/warp_shuffle_vs2019.vcxproj
- Libraries/hipCUB/device_radix_sort/device_radix_sort_vs2019.vcxproj
- Libraries/hipCUB/device_sum/device_sum_vs2019.vcxproj
- Libraries/rocBLAS/level_1/axpy/axpy_vs2019.vcxproj
- Libraries/rocBLAS/level_1/dot/dot_vs2019.vcxproj
- Libraries/rocBLAS/level_1/nrm2/nrm2_vs2019.vcxproj
- Libraries/rocBLAS/level_1/scal/scal_vs2019.vcxproj
- Libraries/rocBLAS/level_1/swap/swap_vs2019.vcxproj
- Libraries/rocBLAS/level_2/gemv/gemv_vs2019.vcxproj
- Libraries/rocBLAS/level_2/her/her_vs2019.vcxproj
- Libraries/rocBLAS/level_3/gemm/gemm_vs2019.vcxproj
- Libraries/rocBLAS/level_3/gemm_strided_batched/gemm_strided_batched_vs2019.vcxproj
- Libraries/rocPRIM/block_sum/block_sum_vs2019.vcxproj
- Libraries/rocPRIM/device_sum/device_sum_vs2019.vcxproj
- Libraries/rocRAND/simple_distributions_cpp/simple_distributions_cpp_vs2019.vcxproj
- Libraries/rocThrust/device_ptr/device_ptr_vs2019.vcxproj
- Libraries/rocThrust/norm/norm_vs2019.vcxproj
- Libraries/rocThrust/reduce_sum/reduce_sum_vs2019.vcxproj
- Libraries/rocThrust/remove_points/remove_points_vs2019.vcxproj
- Libraries/rocThrust/saxpy/saxpy_vs2019.vcxproj
- Libraries/rocThrust/vectors/vectors_vs2019.vcxproj

### CODE REVIEW

**Comment by saadrahim** [comment]
I still the think the toolchains should be called HIP_COMPILER_CLANG and HIP_COMPILER_NVCC. That way it corresponds to the Linux definitions. In Linux, we use HIP_COMPILER to distinguish this functionality.

**Comment by saadrahim** [comment]
@Snektron Why did you close this?

**Comment by Snektron** [comment]
@saadrahim excuses. I used the github web UI to merge this MR: https://github.com/amd/rocm-examples/pull/18, and after that i deleted its associated branch. I think it was automatically closed because this PR targets that branch, instead of being retargeted to the `develop` branch.

Github may allow to retarget the branch now and re-open the PR that way, but I dont see any button for that.

**Comment by emankov** [comment]
> I still the think the toolchains should be called HIP_COMPILER_CLANG and HIP_COMPILER_NVCC. That way it corresponds to the Linux definitions. In Linux, we use HIP_COMPILER to distinguish this functionality.

The approved names for Visual Studio HIP Platform toolsets are `AMD HIP for clang Compiler` and `AMD HIP for nvcc Compiler` for AMD ROCm HIP and NVIDIA CUDA correspondingly. Their short forms (appearing in brackets after the project name in the `Solution Explorer`) are `HIP_clang` and `HIP_nvcc`. As for `HIP_COMPILER`, it is just an env. var.

**Comment by emankov** [comment]
Hello Colleagues,

Are we going to merge the above `vcxproj` changes finally or are we going to continue discussing the naming?
Without those changes, nothing won't work in VS.

Btw, why VS 2022 is not supported in rocm-examples?

Regards,
Evgeny

**Pull request closed without merging**
