### PR TITLE
hipBLAS examples

### PR DESCRIPTION
**Pull request by Snektron**
New examples:
* hipBLAS
    * scal
    * her
    * gemm

### CODE REVIEW

**Comment by saadrahim** [comment]
Update the copyright year to 2022-2023?

**Review by saadrahim — APPROVED** [review]
Please ensure to merge squash.

**Comment by Snektron** [comment]
Should we add that to this PR or is a follow-up fine? Should the copyright be updated for all examples or just the relevant ones?

**Comment by saadrahim** [comment]
> Should we add that to this PR or is a follow-up fine? Should the copyright be updated for all examples or just the relevant ones?

Just relevant ones, only when modifying.

**Pull request merged**
