### PR TITLE
Adding Example for Address Sanitizer

### PR DESCRIPTION
**Pull request by Rmalavally**

### CODE REVIEW

**Review by scartwr — APPROVED** [review]
Works for me. May want to confirm with Saad as well.

**Comment by Snektron** [comment]
This pull request is empty?

**Comment by Rmalavally** [comment]
Let me check. This file is obsolete; i had added a new file. 

https://github.com/Rmalavally/rocm-examples/blob/Rmalavally-patch-1/LLVM_ASAN/Using-Address-Sanitizer-with-a-Short-HIP-Application.md

@Snektron @saadrahim 

Will send a PR.

**Comment by Rmalavally** [comment]
@scartwr @saadrahim https://github.com/amd/rocm-examples/pull/43

**Review by samjwu — APPROVED** [review]

**Comment by Rmalavally** [comment]
@saadrahim Please approve and merge when you have a moment. Urgent requirement for a customer.

@b-sumner

**Review by emankov — APPROVED** [review]
LGTM

**Comment by Rmalavally** [comment]
@saadrahim Could you please approve this merge? This will allow me to merge the example and update the link on the ROCm documentation portal. Thanks so much.

**Pull request merged**
