### PR TITLE
Add cmake-format to CI

### PR DESCRIPTION
**Pull request by dgaliffiAMD**

### CODE REVIEW

**Comment by Naraenda** [comment]
`cmake-format` seems to be no longer maintained: [last update 3 years ago](https://github.com/cheshirekow/cmake_format). Can something like [`gersemi`](https://github.com/BlankSpruce/gersemi) be a better alternative?

**Comment by dgaliffiAMD** [comment]
> `cmake-format` seems to be no longer maintained: [last update 3 years ago](https://github.com/cheshirekow/cmake_format). Can something like [`gersemi`](https://github.com/BlankSpruce/gersemi) be a better alternative?

Thanks! I'm not familiar with `gersemi`, outside of Norse mythology. The usage looks similar to `cmake-format`, so it should be an easy patch.  I'll look into it. :)

**Review by Naraenda — APPROVED** [review]
LGTM, thanks!

**Review by Beanavil — APPROVED** [review]

**Comment by dgaliffiAMD** [comment]
Thanks for the tip, @Naraenda . Gersemi was nice to work with. Similar to cmake-format but with some nice quality-of-life improvements, like accepting the directory as a source.

**Pull request merged**
